CACHE_TTL_SECONDS = 3600
SHORT_CACHE_TTL_SECONDS = 300
LONG_CACHE_TTL_SECONDS = 86400

MAX_CHAT_MESSAGE_LENGTH = 8000
MAX_RETRIEVAL_RESULTS = 20
DEFAULT_CONFIDENCE_THRESHOLD = 70

SYSTEM_PROMPT_CONTEXT_ENGINE = "chronos_context_engine"
SYSTEM_PROMPT_NEWS_INGESTION = "chronos_news_ingestion"
SYSTEM_PROMPT_MEMORY_RECALL = "chronos_memory_recall"
